### ISSUE TITLE
Stuck at execution

### ISSUE THREAD

**Issue by seinecle** [moditect/layrry#64]
I have a simple maven project that creates layers. Using NetBeans 12.1. I install the launcher-all.jar and platform.jar locally. Yet the execution of the project fails with:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< net.clementlevallois:layrry-test >------------------
[INFO] Building layrry-test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ layrry-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\levallois\Google Drive\open\layrry-test\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ layrry-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:exec (default-cli) @ layrry-test ---
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/levallois/.m2/repository/org/moditect/layrry/layrry-launcher/1.0-SNAPSHOT/layrry-launcher-1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/levallois/.m2/repository/org/slf4j/slf4j-simple/1.7.29/slf4j-simple-1.7.29.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
nov. 28, 2020 4:13:04 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNING: Failed downloading org/moditect/layrry/layrry-aggregator/1.0-SNAPSHOT/maven-metadata.xml from https://repo1.maven.org/maven2/. Reason: 
org.eclipse.aether.transfer.MetadataNotFoundException: Could not find metadata org.moditect.layrry:layrry-aggregator:1.0-SNAPSHOT/maven-metadata.xml in central (https://repo1.maven.org/maven2)
Exception in thread "main" java.lang.module.FindException: Unable to derive module descriptor for C:\Users\LEVALL~1\AppData\Local\Temp\layrry-plugins2751936294030724511\0-null-plugins\layrry-launcher-1.0-SNAPSHOT-all.jar
	at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:648)
	at java.base/jdk.internal.module.ModulePath.readModule(ModulePath.java:331)
	at java.base/jdk.internal.module.ModulePath.scanDirectory(ModulePath.java:284)
	at java.base/jdk.internal.module.ModulePath.scan(ModulePath.java:232)
	at java.base/jdk.internal.module.ModulePath.scanNextEntry(ModulePath.java:190)
	at java.base/jdk.internal.module.ModulePath.findAll(ModulePath.java:166)
	at org.moditect.layrry.internal.LayersImpl.createModuleLayer(LayersImpl.java:168)
	at org.moditect.layrry.internal.LayersImpl.run(LayersImpl.java:119)
	at net.clementlevallois.layrry.test.LayrryLauncher.main(LayrryLauncher.java:28)
Caused by: java.lang.module.InvalidModuleDescriptorException: Provider class org.jboss.shrinkwrap.resolver.api.loadable.SpiServiceLoader not in module
	at java.base/jdk.internal.module.ModulePath.deriveModuleDescriptor(ModulePath.java:555)
	at java.base/jdk.internal.module.ModulePath.readJar(ModulePath.java:644)
	... 8 more
```
Why would layrry-aggregator be needed?

**Comment by seinecle** [comment]
Sorry just a noob struggling here, I sorted it out.
