### ISSUE TITLE
Invoking LayrryLauncher with no args should print usage and quit

### ISSUE THREAD

**Issue by aalmiray** [moditect/layrry#81]
Currently it prints an exception and quits

```sh
Exception in thread "main" com.beust.jcommander.ParameterException: The following option is required: [--layers-config]
	at com.beust.jcommander.JCommander.validateOptions(JCommander.java:388)
	at com.beust.jcommander.JCommander.parse(JCommander.java:357)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at org.moditect.layrry.launcher.LayrryLauncher.launch(LayrryLauncher.java:50)
	at org.moditect.layrry.launcher.LayrryLauncher.main(LayrryLauncher.java:41)
```

**Comment by gunnarmorling** [comment]
Oh yes, indeed.

>

**Comment by gunnarmorling** [comment]
I also thought we discussed at some point to make --layers-config optional,
defaulting to layers.yaml|toml in the current directory.

>

**Comment by aalmiray** [comment]
Though to be fully compatible with all possible configured parsers the code should iterate over every available `LayersConfigParser` instance and check if `"layers." + parser.getPreferredFileExtension()` exists in the current launch directory.

**Comment by gunnarmorling** [comment]
Yes, that'd be the perfect solution.

>
